apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-app
  labels:
    app: contacts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contacts
  template:
    metadata:
      labels:
        app: contacts
    spec:
      containers:
      - name: contacts
        image: aritrasaha18/contacts:1.0.0
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "256Mi"
        ports:
        - containerPort: 8092
---
apiVersion: v1
kind: Service
metadata:
  name: contacts-service
  labels:
    app: contacts
spec:
  selector:
    app: contacts
  ports:
  - name: http
    port: 8092
    targetPort: 8092
  type: LoadBalancer
