apiVersion: apps/v1
kind: Deployment
metadata:
  name: databasedb-app
spec:
  selector:
    matchLabels:
      app: databasedb-app
  replicas: 1
  template:
    metadata:
      labels:
        app: databasedb-app
    spec:
      containers:
        - name: databasedb-container
          image: aritrasaha18/db:1.0.0
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "256Mi"
          env:
          - name: MONGODB
            valueFrom:
             configMapKeyRef:
              name: application-configmap
              key: databasedb_url
          ports:
             - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: databasedb-service
spec:
  selector:
    app: databasedb-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer
