apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-app
  labels:
    app: realtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realtime
  template:
    metadata:
      labels:
        app: realtime
    spec:
      containers:
      - name: realtime
        image: aritrasaha18/realtime:1.0.0
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "256Mi"
        ports:
        - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: realtime-service
  labels:
    app: realtime
spec:
  selector:
    app: realtime
  ports:
  - name: http
    port: 8086
    targetPort: 8086
  type: LoadBalancer
